"""
Generate the docs from metadata/: the schema doc and the metric definitions.

    python -m people_ai.metadata.render_docs            write both docs
    python -m people_ai.metadata.render_docs --check    exit 1 if either doc on disk is out of date
    python -m people_ai.metadata.render_docs --facts    show each fact's live value next to its expected value

The templates hold the narrative. Placeholders:
    schema_doc_template.md:  {{fact:<id>}} {{table:<id>}} {{entity_map}} {{tables_reference}}
                             {{placeholder_columns}} {{sensitivity_levels}} {{time_kinds}}
    metric_doc_template.md:  {{dimensions}} {{metrics_index}} {{metrics_reference}}
"""
import argparse
import re
import sys

from people_ai.config import DB_PATH, REPO_ROOT
from people_ai.metadata.catalog import METADATA_DIR, load_catalog
from people_ai.metadata.facts import connect, evaluate, load_facts, normalize
from people_ai.semantic.definitions import load_metrics

TEMPLATE = METADATA_DIR / "schema_doc_template.md"
OUTPUT = REPO_ROOT / "docs" / "Synthetic_Talent_Lifecycle_Schema.md"
METRIC_TEMPLATE = METADATA_DIR / "metric_doc_template.md"
METRIC_OUTPUT = REPO_ROOT / "docs" / "metric_definitions.md"
BANNER = ("<!-- Generated by `python -m people_ai.metadata.render_docs` from metadata/tables.yaml, "
          "metadata/facts.yaml and metadata/schema_doc_template.md. Edit those, not this file. -->\n\n")
PLACEHOLDER = re.compile(r"\{\{\s*(\w+)(?::(\w+))?\s*\}\}")


def fmt(value, plain=False):
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return str(value).lower()
    if isinstance(value, int):
        return str(value) if plain else f"{value:,}"
    return str(value)


def cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ")


def render_fact(fact):
    if fact.expected is None:
        raise ValueError(f"fact {fact.id} has no expected value yet")
    return fmt(normalize(fact.expected), plain="value" in fact.plain)


def render_fact_table(fact):
    if fact.expected is None:
        raise ValueError(f"fact {fact.id} has no expected value yet")
    lines = ["| " + " | ".join(fact.columns) + " |", "|" + "---|" * len(fact.columns)]
    for row in normalize(fact.expected):
        lines.append("| " + " | ".join(cell(fmt(v, plain=col in fact.plain)) for col, v in zip(fact.columns, row)) + " |")
    return "\n".join(lines)


def entity_map(catalog):
    edges = {}
    for t in catalog.tables:
        for c in t.columns:
            if c.references:
                edges.setdefault((c.references.split(".")[0], t.name), []).append(c.name)
    lines = ["```mermaid", "erDiagram"]
    lines += [f'  {parent} ||--o{{ {child} : "{", ".join(cols)}"' for (parent, child), cols in edges.items()]
    return "\n".join(lines + ["```"])


def column_notes(con, table, column):
    notes = [column.description]
    if column.placeholder:
        notes.append("Placeholder: NULL until the text step runs (section 9).")
    elif column.nullable:
        notes.append(f"NULL means {column.null_means}.")
    if column.allowed_values is not None:
        counts = dict(con.execute(f'select "{column.name}", count(*) from "{table.name}" group by 1').fetchall())
        notes.append("Values: " + " · ".join(f"`{fmt(v)}` {counts.get(v, 0):,}" for v in column.allowed_values) + ".")
    if column.range is not None:
        notes.append(f"Range {fmt(column.range[0], plain=True)} to {fmt(column.range[1], plain=True)}.")
    if column.pattern:
        notes.append(f"Format `{column.pattern}`.")
    if column.references:
        notes.append(f"References `{column.references}`.")
    if column.sensitivity:
        notes.append(f"Sensitivity: **{column.sensitivity}**.")
    return cell(" ".join(notes))


def tables_reference(con, catalog):
    out = []
    for area, title in catalog.areas.items():
        out.append(f"### {title}\n")
        for t in (t for t in catalog.tables if t.area == area):
            rows = con.execute(f'select count(*) from "{t.name}"').fetchone()[0]
            keys = []
            if t.primary_key:
                keys.append("primary key " + ", ".join(f"`{c}`" for c in t.primary_key))
            keys += ["unique " + ", ".join(f"`{c}`" for c in u) for u in t.unique]
            out += [f"#### `{t.name}`\n", t.description, "",
                    f"- **Grain:** {t.grain} ({rows:,} rows)",
                    f"- **Keys:** {'; '.join(keys)}",
                    f"- **Time:** {t.time}. {catalog.time_kinds[t.time]}",
                    f"- **Sensitivity:** {t.sensitivity}", ""]
            if t.rules:
                out += ["Rules:", *[f"- {r}" for r in t.rules], ""]
            out += ["| column | type | meaning |", "|---|---|---|"]
            out += [f"| `{c.name}` | {c.type} | {column_notes(con, t, c)} |" for c in t.columns]
            out.append("")
    return "\n".join(out).rstrip()


def placeholder_columns(catalog):
    lines = ["| column | generate from | lets you practice |", "|---|---|---|"]
    for t in catalog.tables:
        for c in t.columns:
            if c.placeholder:
                lines.append(f"| `{t.name}.{c.name}` | {cell(c.placeholder.generate_from)} | {cell(c.placeholder.practice)} |")
    return "\n".join(lines)


def render(con, catalog, facts):
    def substitute(match):
        kind, arg = match.group(1), match.group(2)
        if kind == "fact":
            return render_fact(facts.get(arg))
        if kind == "table":
            return render_fact_table(facts.get(arg))
        if kind == "entity_map":
            return entity_map(catalog)
        if kind == "tables_reference":
            return tables_reference(con, catalog)
        if kind == "placeholder_columns":
            return placeholder_columns(catalog)
        if kind == "sensitivity_levels":
            return "\n".join(f"- **{k}:** {v}" for k, v in catalog.sensitivity_levels.items())
        if kind == "time_kinds":
            return "\n".join(f"- **{k}:** {v}" for k, v in catalog.time_kinds.items())
        raise ValueError(f"unknown placeholder {match.group(0)}")

    return BANNER + PLACEHOLDER.sub(substitute, TEMPLATE.read_text())


def metrics_index(registry):
    lines = ["| metric | what it answers | period | breakdowns |", "|---|---|---|---|"]
    for metric in registry.metrics:
        first_sentence = metric.definition.split(". ")[0].rstrip(".") + "."
        lines.append(f"| [`{metric.name}`](#{metric.name}) | {cell(first_sentence)} | {metric.period} | "
                     f"{', '.join(f'`{b}`' for b in metric.breakdowns) or '—'} |")
    return "\n".join(lines)


def metrics_reference(registry):
    out = []
    for metric in registry.metrics:
        roles = lambda level: ", ".join(f"`{r}`" for r in metric.access.get(level, ())) or "nobody"
        out += [f"### `{metric.name}`\n", f"**{metric.title}.** {metric.definition}\n",
                f"- **Grain:** {metric.grain}",
                f"- **Period:** {metric.period}",
                f"- **Leader counts in their own tree:** {'yes' if metric.leader_included else 'no'}",
                f"- **Sensitivity:** {metric.sensitivity} — individual rows: {roles('individual')}; aggregates: {roles('aggregate')}",
                f"- **Reads:** {', '.join(f'`{s}`' for s in metric.sources)}",
                f"- **Breakdowns:** {', '.join(f'`{b}`' for b in metric.breakdowns) or 'none'}", ""]
        out += ["Parameters:", *[f"- `{p['name']}` — {p['description']}" for p in metric.parameters], ""]
        out += ["Returns:", *[f"- `{v['name']}` — {v['description']}" for v in metric.value_columns], ""]
        if metric.edge_cases:
            out += ["Edge cases:", *[f"- {e}" for e in metric.edge_cases], ""]
        if metric.verified_by:
            out += [f"Verified against facts: {', '.join(f'`{f}`' for f in metric.verified_by)}", ""]
    return "\n".join(out).rstrip()


def render_metrics(registry=None):
    registry = registry or load_metrics()
    replacements = {
        "dimensions": "\n".join(f"- **`{name}`** — {text}" for name, text in registry.dimensions.items()),
        "metrics_index": metrics_index(registry),
        "metrics_reference": metrics_reference(registry),
    }

    def substitute(match):
        if match.group(1) not in replacements:
            raise ValueError(f"unknown placeholder {match.group(0)}")
        return replacements[match.group(1)]

    return BANNER.replace("metadata/tables.yaml, metadata/facts.yaml and metadata/schema_doc_template.md",
                          "metadata/metrics.yaml and metadata/metric_doc_template.md") + \
        PLACEHOLDER.sub(substitute, METRIC_TEMPLATE.read_text())


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="exit 1 if the doc is out of date")
    parser.add_argument("--facts", action="store_true", help="compare every fact with the live data")
    args = parser.parse_args(argv)

    catalog, facts = load_catalog(), load_facts()
    con = connect(DB_PATH, facts)
    if args.facts:
        differences = 0
        for fact in facts.facts:
            live, expected = evaluate(con, fact), normalize(fact.expected)
            same = live == expected
            differences += not same
            print(f"{'ok  ' if same else 'DIFF'} {fact.id}\n       expected: {expected!r}\n       live:     {live!r}")
        print(f"\n{len(facts.facts) - differences} match, {differences} differ")
        return 1 if differences else 0

    documents = [(OUTPUT, render(con, catalog, facts)), (METRIC_OUTPUT, render_metrics())]
    if args.check:
        stale = [path.name for path, text in documents if not path.exists() or path.read_text() != text]
        print(f"out of date: {', '.join(stale)} (run python -m people_ai.metadata.render_docs)" if stale
              else "docs are up to date")
        return int(bool(stale))
    for path, text in documents:
        path.write_text(text)
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
